plugins {
    id 'java'
    id 'net.neoforged.moddev' version '1.0.21'
}

version = mod_version
group = mod_group_id
base { archivesName = mod_id }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
    withSourcesJar()
}

repositories {
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    mavenCentral()
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = "2024.11.17"
        minecraftVersion = "1.21.1"
    }

    runs {
        client {
            client()
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            programArguments.addAll '--username', 'Dev'
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        playerragdoll {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

processResources {
    var replaceProperties = [
        mod_id               : mod_id,
        mod_name             : mod_name,
        mod_version          : mod_version,
        mod_authors          : mod_authors,
        mod_description      : mod_description,
        neo_version_range    : neo_version_range,
        loader_version_range : loader_version_range,
        minecraft_version_range: minecraft_version_range
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

dependencies {}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes([
            'Specification-Title'    : 'playerragdoll',
            'Specification-Vendor'   : 'YourName',
            'Specification-Version'  : '1',
            'Implementation-Title'   : 'playerragdoll',
            'Implementation-Version' : project.version,
            'Implementation-Vendor'  : 'YourName',
        ])
    }
}
