modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/yourname/playerragdoll/issues"

[[mods]]
    modId          = "${mod_id}"
    version        = "${mod_version}"
    displayName    = "${mod_name}"
    description    = '''${mod_description}'''
    authors        = "${mod_authors}"

[[dependencies.playerragdoll]]
    modId      = "neoforge"
    type       = "required"
    versionRange = "${neo_version_range}"
    ordering   = "NONE"
    side       = "BOTH"

[[dependencies.playerragdoll]]
    modId      = "minecraft"
    type       = "required"
    versionRange = "${minecraft_version_range}"
    ordering   = "NONE"
    side       = "BOTH"
